-- MySQL Script generated by MySQL Workbench
-- mar. 06 nov. 2018 09:45:54 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema dutinfopw201622
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dutinfopw201622` ;

-- -----------------------------------------------------
-- Schema dutinfopw201622
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dutinfopw201622` DEFAULT CHARACTER SET utf8 ;
USE `dutinfopw201622` ;

-- -----------------------------------------------------
-- Table `dutinfopw201622`.`filliere_bac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`filliere_bac` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`filliere_bac` (
  `id_filliere_bac` VARCHAR(20) NOT NULL,
  `nom_filliere_bac` VARCHAR(90) NULL,
  PRIMARY KEY (`id_filliere_bac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`pays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`pays` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`pays` (
  `code_pays` VARCHAR(5) NOT NULL,
  `nom_pays` VARCHAR(45) NULL,
  `nationalite` VARCHAR(45) NULL,
  PRIMARY KEY (`code_pays`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`Ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`Ville` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`Ville` (
  `code_postal_ville` VARCHAR(8) NOT NULL,
  `nom_ville` VARCHAR(65) NULL,
  PRIMARY KEY (`code_postal_ville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `pseudo_utilisateur` VARCHAR(45) NULL,
  `mail_utilisateur` VARCHAR(200) NULL,
  `nom_utilisateur` VARCHAR(45) NULL,
  `prenom_utilisateur` VARCHAR(45) NULL,
  `tel_utilisateur` VARCHAR(10) NULL,
  `adresse_utilisateur` VARCHAR(150) NULL,
  `est_homme` TINYINT NULL,
  `date_naissance_utilisateur` DATE NULL,
  `mot_de_passe_utilisateur` VARCHAR(60) NULL,
  `cle_recuperation_mdp` VARCHAR(80) ,
  `date_creation_compte` DATE ,
  `id_filliere_bac` VARCHAR(20) NULL,
  `code_pays` VARCHAR(5) NULL,
  `code_postal_ville` VARCHAR(8) NULL,
  PRIMARY KEY (`id_utilisateur`),
  CONSTRAINT `fk_utilisateur_filliere_bac1`
    FOREIGN KEY (`id_filliere_bac`)
    REFERENCES `dutinfopw201622`.`filliere_bac` (`id_filliere_bac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_pays1`
    FOREIGN KEY (`code_pays`)
    REFERENCES `dutinfopw201622`.`pays` (`code_pays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_Ville1`
    FOREIGN KEY (`code_postal_ville`)
    REFERENCES `dutinfopw201622`.`Ville` (`code_postal_ville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pseudo_utilisateur_UNIQUE` ON `dutinfopw201622`.`utilisateur` (`pseudo_utilisateur` ASC);

CREATE UNIQUE INDEX `mail_utilisateur_UNIQUE` ON `dutinfopw201622`.`utilisateur` (`mail_utilisateur` ASC);


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`droits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`droits` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`droits` (
  `nom_droits` VARCHAR(60) NOT NULL,
  `droit_creation_groupes` TINYINT NULL,
  `droit_creation_modules` TINYINT NULL,
  `droit_creation_lecons` TINYINT NULL,
  `droit_creation_utilisateurs` TINYINT NULL,
  `droit_modification_absences` TINYINT NULL,
  `droit_modification_droits` TINYINT NULL,
  `droit_modification_edt` TINYINT NULL,
  `droit_modification_donnees_utilisateur` TINYINT NULL,
  `droit_modification_heures_travail` TINYINT NULL,
  `droit_visualisation_stats` TINYINT NULL,
  `droit_visualisation_heures_travail` TINYINT NULL,
  PRIMARY KEY (`nom_droits`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`a_droits_de`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`a_droits_de` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`a_droits_de` (
  `nom_droits` VARCHAR(60) NOT NULL,
  `id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`nom_droits`, `id_utilisateur`),
  CONSTRAINT `fk_table2_has_table1_table2`
    FOREIGN KEY (`nom_droits`)
    REFERENCES `dutinfopw201622`.`droits` (`nom_droits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_has_table1_table11`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `dutinfopw201622`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`groupe` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`groupe` (
  `id_groupe` INT NOT NULL AUTO_INCREMENT,
  `nom_groupe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_groupe`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nom_groupe_UNIQUE` ON `dutinfopw201622`.`groupe` (`nom_groupe` ASC);


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`ont_droits_de`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`ont_droits_de` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`ont_droits_de` (
  `nom_droits` VARCHAR(60) NOT NULL,
  `id_groupe` INT NOT NULL,
  PRIMARY KEY (`nom_droits`, `id_groupe`),
  CONSTRAINT `fk_droits_has_groupe_droits1`
    FOREIGN KEY (`nom_droits`)
    REFERENCES `dutinfopw201622`.`droits` (`nom_droits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_droits_has_groupe_groupe1`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `dutinfopw201622`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`utilisateur_appartient_a_groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`utilisateur_appartient_a_groupe` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`utilisateur_appartient_a_groupe` (
  `id_groupe` INT NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `utilisateur_appartient_a_groupecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_groupe`, `id_utilisateur`),
  CONSTRAINT `fk_groupe_has_utilisateur_groupe1`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `dutinfopw201622`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupe_has_utilisateur_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `dutinfopw201622`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`etudiant` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`etudiant` (
  `numero_etudiant` VARCHAR(15) NOT NULL,
  `points_ets_etudiant` INT NULL,
  `id_utilisateur` INT NULL,
  PRIMARY KEY (`numero_etudiant`),
  CONSTRAINT `fk_etudiant_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `dutinfopw201622`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_utilisateur_UNIQUE` ON `dutinfopw201622`.`etudiant` (`id_utilisateur` ASC);


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`est_un_sous_groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`est_un_sous_groupe` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`est_un_sous_groupe` (
  `id_groupe_parent` INT NOT NULL,
  `id_groupe_fils` INT NOT NULL,
  PRIMARY KEY (`id_groupe_parent`, `id_groupe_fils`),
  CONSTRAINT `fk_groupe_has_groupe_groupe1`
    FOREIGN KEY (`id_groupe_parent`)
    REFERENCES `dutinfopw201622`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupe_has_groupe_groupe2`
    FOREIGN KEY (`id_groupe_fils`)
    REFERENCES `dutinfopw201622`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`personnel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`personnel` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`personnel` (
  `id_personnel` INT NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `formation_personnel` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_personnel`, `id_utilisateur`),
  CONSTRAINT `fk_personnel_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `dutinfopw201622`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`mission_personnel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`mission_personnel` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`mission_personnel` (
  `id_mission` VARCHAR(30) NOT NULL,
  `nom_misssion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_mission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`personnel_a_pour_misssion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`personnel_a_pour_misssion` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`personnel_a_pour_misssion` (
  `personnel_id_personnel` INT NOT NULL,
  `mission_personnel_id_mission` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`personnel_id_personnel`, `mission_personnel_id_mission`),
  CONSTRAINT `fk_personnel_has_mission_personnel_personnel1`
    FOREIGN KEY (`personnel_id_personnel`)
    REFERENCES `dutinfopw201622`.`personnel` (`id_personnel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnel_has_mission_personnel_mission_personnel1`
    FOREIGN KEY (`mission_personnel_id_mission`)
    REFERENCES `dutinfopw201622`.`mission_personnel` (`id_mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`departement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`departement` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`departement` (
  `id_departement` INT NOT NULL,
  `nom_departement` VARCHAR(45) NULL,
  `id_personnel_responsable` INT NOT NULL,
  PRIMARY KEY (`id_departement`),
  CONSTRAINT `fk_departement_personnel1`
    FOREIGN KEY (`id_personnel_responsable`)
    REFERENCES `dutinfopw201622`.`personnel` (`id_personnel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`formation_proposes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`formation_proposes` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`formation_proposes` (
  `id_formation` INT NOT NULL,
  `nom_formation` VARCHAR(80) NULL,
  `id_departement_concerne` INT NOT NULL,
  PRIMARY KEY (`id_formation`),
  CONSTRAINT `fk_formation_proposes_departement1`
    FOREIGN KEY (`id_departement_concerne`)
    REFERENCES `dutinfopw201622`.`departement` (`id_departement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`type_semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`type_semestre` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`type_semestre` (
  `id_type_semestre` INT NOT NULL,
  `nom_type_semestre` VARCHAR(200) NULL,
  `points_ets_semestre` MEDIUMINT(9) NULL,
  `id_formation` INT NOT NULL,
  PRIMARY KEY (`id_type_semestre`),
  CONSTRAINT `fk_type_semestre_formation_proposes1`
    FOREIGN KEY (`id_formation`)
    REFERENCES `dutinfopw201622`.`formation_proposes` (`id_formation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`module` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`module` (
  `id_module` INT NOT NULL AUTO_INCREMENT,
  `reference_module` VARCHAR(8) NULL,
  `nom_module` VARCHAR(45) NULL,
  `coefficient_module` FLOAT NULL,
  `heures_cm_module` FLOAT NULL,
  `heures_td_module` FLOAT NULL,
  `heures_tp_module` FLOAT NULL,
  `type_semestre` INT NOT NULL,
  PRIMARY KEY (`id_module`),
  CONSTRAINT `fk_module_type_semestre1`
    FOREIGN KEY (`type_semestre`)
    REFERENCES `dutinfopw201622`.`type_semestre` (`id_type_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`enseignant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`enseignant` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`enseignant` (
  `num_enseignant` INT NOT NULL AUTO_INCREMENT,
  `id_personnel` INT NOT NULL,
  PRIMARY KEY (`num_enseignant`),
  CONSTRAINT `fk_enseignant_personnel2`
    FOREIGN KEY (`id_personnel`)
    REFERENCES `dutinfopw201622`.`personnel` (`id_personnel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_personnel_UNIQUE` ON `dutinfopw201622`.`enseignant` (`id_personnel` ASC);


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`annee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`annee` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`annee` (
  `annee` INT NOT NULL,
  PRIMARY KEY (`annee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`heures_travail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`heures_travail` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`heures_travail` (
  `id_heures_travail` INT NOT NULL,
  `heures_travail` INT(11) NULL,
  `annee` INT NOT NULL,
  `num_enseignant` INT NOT NULL,
  PRIMARY KEY (`id_heures_travail`),
  CONSTRAINT `fk_heures_travail_annee1`
    FOREIGN KEY (`annee`)
    REFERENCES `dutinfopw201622`.`annee` (`annee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_heures_travail_enseignant1`
    FOREIGN KEY (`num_enseignant`)
    REFERENCES `dutinfopw201622`.`enseignant` (`num_enseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`module_enseigner_par`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`module_enseigner_par` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`module_enseigner_par` (
  `enseignant_num_enseignant` INT NOT NULL,
  `module_id_module` INT NOT NULL,
  PRIMARY KEY (`enseignant_num_enseignant`, `module_id_module`),
  CONSTRAINT `fk_enseignant_has_module_enseignant1`
    FOREIGN KEY (`enseignant_num_enseignant`)
    REFERENCES `dutinfopw201622`.`enseignant` (`num_enseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enseignant_has_module_module1`
    FOREIGN KEY (`module_id_module`)
    REFERENCES `dutinfopw201622`.`module` (`id_module`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`semestre` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`semestre` (
  `id_semestre` INT NOT NULL,
  `nom_semestre` VARCHAR(90) NULL,
  `annee_semestre` INT NOT NULL,
  `id_groupe_semestre` INT NOT NULL,
  `points_semestre` VARCHAR(45) NULL,
  `type_semestre_id_type_semestre` INT NOT NULL,
  PRIMARY KEY (`id_semestre`),
  CONSTRAINT `fk_semstres_annee1`
    FOREIGN KEY (`annee_semestre`)
    REFERENCES `dutinfopw201622`.`annee` (`annee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semstre_groupe1`
    FOREIGN KEY (`id_groupe_semestre`)
    REFERENCES `dutinfopw201622`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semstre_type_semestre1`
    FOREIGN KEY (`type_semestre_id_type_semestre`)
    REFERENCES `dutinfopw201622`.`type_semestre` (`id_type_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`batiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`batiment` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`batiment` (
  `id_batiment` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_batiment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`type_salle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`type_salle` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`type_salle` (
  `type_salle` INT NOT NULL,
  PRIMARY KEY (`type_salle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`salle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`salle` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`salle` (
  `id_salle` INT NOT NULL,
  `nom_salle` VARCHAR(45) NULL,
  `type_salle` INT NOT NULL,
  `id_batiment` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_salle`),
  CONSTRAINT `fk_salle_type_salle1`
    FOREIGN KEY (`type_salle`)
    REFERENCES `dutinfopw201622`.`type_salle` (`type_salle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salle_batiment1`
    FOREIGN KEY (`id_batiment`)
    REFERENCES `dutinfopw201622`.`batiment` (`id_batiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`batiments_de_departement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`batiments_de_departement` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`batiments_de_departement` (
  `departement_id_departement` INT NOT NULL,
  `batiment_id_batiment` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`departement_id_departement`, `batiment_id_batiment`),
  CONSTRAINT `fk_departement_has_batiment_departement1`
    FOREIGN KEY (`departement_id_departement`)
    REFERENCES `dutinfopw201622`.`departement` (`id_departement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departement_has_batiment_batiment1`
    FOREIGN KEY (`batiment_id_batiment`)
    REFERENCES `dutinfopw201622`.`batiment` (`id_batiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`jour_travail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`jour_travail` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`jour_travail` (
  `id_jour_travail` INT NOT NULL,
  `jour_travail` DATE NULL,
  `id_departement` INT NOT NULL,
  `annee` INT NOT NULL,
  PRIMARY KEY (`id_jour_travail`),
  CONSTRAINT `fk_jour_travail_departement1`
    FOREIGN KEY (`id_departement`)
    REFERENCES `dutinfopw201622`.`departement` (`id_departement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jour_travail_annee1`
    FOREIGN KEY (`annee`)
    REFERENCES `dutinfopw201622`.`annee` (`annee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`type_seance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`type_seance` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`type_seance` (
  `id_type_seance` VARCHAR(10) NOT NULL,
  `nom_complet_type_seance` VARCHAR(45) NOT NULL,
  `couleur_seance` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_type_seance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dutinfopw201622`.`seance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dutinfopw201622`.`seance` ;

CREATE TABLE IF NOT EXISTS `dutinfopw201622`.`seance` (
  `id_seance` INT NOT NULL,
  `heure_depart` TIME NULL,
  `duree_seance` FLOAT NULL,
  `jour_travail` INT NOT NULL,
  `id_groupe` INT NOT NULL,
  `id_type_seance` VARCHAR(10) NOT NULL,
  `id_module` INT NOT NULL,
  PRIMARY KEY (`id_seance`),
  CONSTRAINT `fk_seance_jour_travail1`
    FOREIGN KEY (`jour_travail`)
    REFERENCES `dutinfopw201622`.`jour_travail` (`id_jour_travail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seance_groupe1`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `dutinfopw201622`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seance_type_seance1`
    FOREIGN KEY (`id_type_seance`)
    REFERENCES `dutinfopw201622`.`type_seance` (`id_type_seance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seance_module1`
    FOREIGN KEY (`id_module`)
    REFERENCES `dutinfopw201622`.`module` (`id_module`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

